/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameLogic from "./logic/view_logic/GameLogic"
import TopControlComponent from "./logic/component/TopControlComponent"
import LoadLogic from "./logic/view_logic/LoadLogic"
import NetworkStateComponent from "./logic/component/NetworkStateComponent"
import GameAlertComponent from "./logic/component/GameAlertComponent"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedauto";
    static screenMode:string="vertical";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="MainScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=false;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("logic/view_logic/GameLogic.ts",GameLogic);
        reg("logic/component/TopControlComponent.ts",TopControlComponent);
        reg("logic/view_logic/LoadLogic.ts",LoadLogic);
        reg("logic/component/NetworkStateComponent.ts",NetworkStateComponent);
        reg("logic/component/GameAlertComponent.ts",GameAlertComponent);
    }
}
GameConfig.init();